services:
  db-mongo:
    image: mongo
    volumes:
      - ./my-mongo-db:/data/db
    container_name: container-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb12062021
    ports:
      - 27017:27017
    networks:
      - default
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb12062021
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: mongodb12062021
      ME_CONFIG_MONGODB_URL: mongodb://root:mongodb12062021@container-mongo:27017/
    networks:
      - default
networks:
  default:
    name: loki2
    driver: bridge